CREATE PROCEDURE dbo.UpdateWaterMarkTable
@TableName VARCHAR(100),
@NewWatermark DATETIME2(6)
AS
BEGIN
    UPDATE dbo.WaterMarkTable
    SET Watermark = @NewWatermark
    WHERE TableName = @TableName
END

SELECT ROUTINE_NAME, ROUTINE_SCHEMA 
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_TYPE = 'PROCEDURE'

SELECT * FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_NAME = 'UpdateWaterMarkTable';
